stages:
  - deploy

variables:
  DOCKER_IMAGE_NAME: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/kubernetes-website
  VERSION: release-1.23
  INTERNAL_PORT: 80
  EXTERNAL_PORT: 61523

deploy:
  stage: deploy
  image: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/docker:26.1.3-cli
  variables:
    DOCKER_HOST: $DEPLOY_DOCKER_HOST
  script:
    - docker info
    - docker compose up -d
    - docker images | grep kubernetes-website
    - docker images | grep kubernetes-website | awk '{print $3}' | xargs docker rmi || echo
  environment: production/v1.23
  tags:
    - lighthouse-docker
  rules:
    - if: $DEPLOY == "true"
