stages:
  - deploy

variables:
  DOCKER_IMAGE_NAME: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/kubernetes-website
  VERSION: snapshot-initial-v1.30
  INTERNAL_PORT: 80
  EXTERNAL_PORT: 61580

deploy:
  stage: deploy
  image: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/docker:26.1.3-cli
  variables:
    DOCKER_HOST: $DEPLOY_DOCKER_HOST
  script:
    - docker info
    - docker compose up -d
  environment: production
  tags:
    - lighthouse-docker
  rules:
    - if: $DEPLOY == "true"
