stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.1-debug
    entrypoint: [ "" ]
  variables:
    URL: https://github.com/kubernetes/website/archive/refs/tags/snapshot-initial-v1.30.tar.gz
    TAG: snapshot-initial-v1.30
    NAME: website
  before_script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" ${DOCKER_USERNAME} "${DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - echo $URL
    - NAME=$(basename "$URL")
    - TAG=$(basename "$URL" .tar.gz)
    - echo $TAG
    - wget $URL
    - ls -l
    - mkdir $TAG
    - ls -l
    - tar --strip-components=1 -zxf $NAME -C $TAG
    - ls -l
    - cd $CI_PROJECT_DIR/$TAG
    - ls -l
