stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.1-debug
    entrypoint: [ "" ]
  variables:
    URL: https://github.com/kubernetes/website/archive/refs/tags/snapshot-initial-v1.30.tar.gz
    TAG: snapshot-initial-v1.30
    NAME: website
    HUGO_VERSION: 0.121.2
    DOCKERFILE_ADDITIONAL_CONTENT: |
      ARG CI_PROJECT_DIR
      ARG TAG
      
      RUN cd $CI_PROJECT_DIR/$TAG && ls -l && npm ci && /go/bin/hugo --minify --environment development && ls -l $CI_PROJECT_DIR/$TAG/public
  before_script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" ${DOCKER_USERNAME} "${DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - echo $URL
    - NAME=$(basename "$URL")
    - TAG=$(basename "$URL" .tar.gz)
    - echo $TAG
    - wget $URL
    - ls -l
    - mkdir $TAG
    - ls -l
    - tar --strip-components=1 -zxf $NAME -C $TAG
    - ls -l
    - ls -l $CI_PROJECT_DIR/$TAG
    - cat $CI_PROJECT_DIR/$TAG/Dockerfile
    - sed -i "s#COPY --from=0 /go/bin/hugo /usr/local/bin/hugo##" $CI_PROJECT_DIR/$TAG/Dockerfile
    - sed -i "s#WORKDIR /src##" $CI_PROJECT_DIR/$TAG/Dockerfile
    - sed -i "s#USER hugo:hugo##" $CI_PROJECT_DIR/$TAG/Dockerfile
    - sed -i "s#EXPOSE 1313##" $CI_PROJECT_DIR/$TAG/Dockerfile
    - cat $CI_PROJECT_DIR/$TAG/Dockerfile
    - echo "$DOCKERFILE_ADDITIONAL_CONTENT"
    - echo "$DOCKERFILE_ADDITIONAL_CONTENT" >> $CI_PROJECT_DIR/$TAG/Dockerfile
    - cat $CI_PROJECT_DIR/$TAG/Dockerfile
    - /kaniko/executor version
    - /kaniko/executor --help
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/${TAG}"
      --dockerfile "${CI_PROJECT_DIR}/${TAG}/Dockerfile"
      --build-arg "CI_PIPELINE_URL=${CI_PIPELINE_URL}"
      --build-arg "HUGO_VERSION=${HUGO_VERSION}"
      --build-arg "CI_PROJECT_DIR=${CI_PROJECT_DIR}"
      --build-arg "TAG=${TAG}"
      --destination "xuxiaoweicomcn/kubernetes-website:${TAG}"
      --destination "xuxiaoweicomcn/kubernetes-website:${TAG}-${CI_PIPELINE_ID}"
