stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.1-debug
    entrypoint: [ "" ]
  variables:
    URL: https://github.com/kubernetes/website.git
    TAG: release-1.19
    HUGO_VERSION: 0.74.3
  before_script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" ${DOCKER_USERNAME} "${DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - echo $URL
    - echo $TAG
    - echo $HUGO_VERSION
    - echo $CI_PROJECT_DIR
    - /kaniko/executor version
    - /kaniko/executor --help
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg "URL=${URL}"
      --build-arg "CI_PIPELINE_URL=${CI_PIPELINE_URL}"
      --build-arg "HUGO_VERSION=${HUGO_VERSION}"
      --build-arg "TAG=${TAG}"
      --destination "xuxiaoweicomcn/kubernetes-website:${TAG}"
      --destination "xuxiaoweicomcn/kubernetes-website:${TAG}-${CI_PIPELINE_ID}"
  rules:
    - if: $BUILD == "true"
