stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.1-debug
    entrypoint: [ "" ]
  variables:
    URL: https://github.com/kubernetes/website.git
    TAG: snapshot-initial-v1.30
    NAME: website
  before_script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" ${DOCKER_USERNAME} "${DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - echo $URL
    - echo $TAG
    - git clone --branch $TAG --depth 1 $URL $NAME
    - cd $CI_PROJECT_DIR/$NAME
    - ls -l
