services:
  kubernetes-website-v1.28:
    image: ${DOCKER_IMAGE_NAME}:${VERSION}
    restart: always
    ports:
      - ${EXTERNAL_PORT:-61528}:${INTERNAL_PORT:-80}
    container_name: kubernetes-website-v1.28
